import React,{useState}from"react";
import{ArrowRight,Loader2,Eye,EyeOff,Building2}from"lucide-react";
import{supabase}from"./supabase.js";
export default function Auth({onAuth,initialMode="login"}){
 const[mode,setMode]=useState(initialMode),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[company,setCompany]=useState(""),[show,setShow]=useState(false),[loading,setLoading]=useState(false),[error,setError]=useState(""),[message,setMessage]=useState("");
 async function submit(e){e.preventDefault();setError("");setMessage("");setLoading(true);if(!supabase){setError("Le service d’authentification n’est pas disponible.");setLoading(false);return}
  const redirectTo=window.location.origin+"/auth/callback";
  const r=mode==="login"?await supabase.auth.signInWithPassword({email:email.trim().toLowerCase(),password}):await supabase.auth.signUp({email:email.trim().toLowerCase(),password,options:{emailRedirectTo:redirectTo,data:{company_name:company.trim()}}});
  setLoading(false);if(r.error){setError(r.error.message);return}
  if(mode==="signup"){if(r.data.session)onAuth(r.data.user);else setMessage("Compte créé. Vérifiez votre e-mail : le lien vous renverra directement vers votre dashboard.");}
  else onAuth(r.data.user);
 }
 return <div className="authPage"><div className="authCard"><div className="authLogo"><div className="brandMark">➤</div><div><strong>WhatSend <span>Pro</span></strong><small>Outil professionnel pour WhatsApp Business</small></div></div><div className="authIntro"><div className="eyebrow">ESPACE PROFESSIONNEL</div><h1>{mode==="login"?"Bienvenue sur WhatSend Pro":"Créer votre espace"}</h1><p>{mode==="login"?"Simplifiez l’utilisation de WhatsApp Business depuis un seul espace.":"Créez votre compte et commencez la configuration de votre entreprise."}</p></div><form onSubmit={submit}>{mode==="signup"&&<label><Building2 size={14}/> Entreprise<input value={company} onChange={e=>setCompany(e.target.value)} required placeholder="Nom de votre entreprise"/></label>}<label>E-mail<input value={email} onChange={e=>setEmail(e.target.value)} type="email" required placeholder="vous@entreprise.com"/></label><label>Mot de passe<div className="password"><input value={password} onChange={e=>setPassword(e.target.value)} type={show?"text":"password"} required minLength="8" placeholder="••••••••"/><button type="button" onClick={()=>setShow(!show)}>{show?<EyeOff size={17}/>:<Eye size={17}/>}</button></div></label>{error&&<div className="formError">{error}</div>}{message&&<div className="formSuccess">{message}</div>}<button className="primary full" disabled={loading}>{loading?<Loader2 className="spin" size={17}/>:<ArrowRight size={17}/>} {mode==="login"?"Se connecter":"Créer mon compte"}</button></form><button className="switchAuth" onClick={()=>{setMode(mode==="login"?"signup":"login");setError("");setMessage("")}}>{mode==="login"?"Pas encore de compte ? Créer un espace":"Déjà un compte ? Se connecter"}</button><small className="legal">En créant un compte, vous acceptez les conditions d’utilisation et la politique de confidentialité.</small></div></div>
}